server:
  port: 80
  #GitHub登录
github:
  clientId:
  secret:
  redirectUrl:

# QQ
qq:
  qqClientId:
  qqClientSecret:
  qqRedirectUrl:
# UCloud
ucloud-ufile:
  bucketName:
  expires:
  privateKey:
  publicKey:
  region:
  suffix:
#Spring
spring:
  datasource:
    driver-class-name:
    password:
    url:
    username:
  redis:
    host: localhost
    port: 6379
#Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: life.majiang.community.mapper
#pagehelper插件
pagehelper:
  helperDialect: mysql
  page-size-zero: true
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
#logging日志
logging:
  file:
    max-history: 30
    max-size: 100MB
    name: logs/community.log
  level:
    com:
      example:
        demo:
          dao: DEBUG
    root: info

